openapi: 3.0.3
info:
  title: vscubing Api
  version: 1.0.0
  description: vscubing is a contest platform for speedcubers to compete in virtual
    speedcubing
paths:
  /api/accounts_app/change_username/:
    put:
      operationId: accounts_app_change_username_update
      tags:
      - accounts_app
      security:
      - jwtHeaderAuth: []
      - jwtCookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/accounts_app/current_user/:
    get:
      operationId: accounts_app_current_user_retrieve
      tags:
      - accounts_app
      security:
      - jwtHeaderAuth: []
      - jwtCookieAuth: []
      responses:
        '200':
          description: No response body
  /api/accounts_app/google/login/:
    post:
      operationId: accounts_app_google_login_create
      description: |-
        class used for social authentications
        example usage for facebook with access_token
        -------------
        from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter

        class FacebookLogin(SocialLoginView):
            adapter_class = FacebookOAuth2Adapter
        -------------

        example usage for facebook with code

        -------------
        from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
        from allauth.socialaccount.providers.oauth2.client import OAuth2Client

        class FacebookLogin(SocialLoginView):
            adapter_class = FacebookOAuth2Adapter
            client_class = OAuth2Client
            callback_url = 'localhost:8000'
        -------------
      tags:
      - accounts_app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialLogin'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SocialLogin'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SocialLogin'
      security:
      - jwtHeaderAuth: []
      - jwtCookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialLogin'
          description: ''
  /api/accounts_app/token/refresh/:
    post:
      operationId: accounts_app_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - accounts_app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/contests_app/solves/:
    get:
      operationId: contests_app_solves_retrieve
      parameters:
      - in: query
        name: page
        schema:
          type: integer
        description: page
      - in: query
        name: page_size
        schema:
          type: integer
        description: page size
      tags:
      - contests_app
      security:
      - jwtHeaderAuth: []
      - jwtCookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contests.SolveLisOutput'
          description: ''
  /api/contests_app/solves/{id}/:
    get:
      operationId: contests_app_solves_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - contests_app
      security:
      - jwtHeaderAuth: []
      - jwtCookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/contests_app/solves/list-bests-in-disciplines/:
    get:
      operationId: contests_app_solves_list_bests_in_disciplines_retrieve
      tags:
      - contests_app
      security:
      - jwtHeaderAuth: []
      - jwtCookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contests.SolveListBestsInDisciplinesOutput'
          description: ''
  /api/contests_app/solves/list-every-user-best/:
    get:
      operationId: contests_app_solves_list_every_user_best_list
      description: my description
      parameters:
      - in: query
        name: discipline_name
        schema:
          type: string
        description: discipline name
        required: true
      tags:
      - contests_app
      security:
      - jwtHeaderAuth: []
      - jwtCookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/contests.SolveListBestOfEveryUserOutput'
          description: ''
components:
  schemas:
    Contest:
      type: object
      description: |-
        A ModelSerializer that takes an additional `fields` argument that
        controls which fields should be displayed.
      properties:
        id:
          type: integer
          readOnly: true
        contest_number:
          type: integer
        start:
          type: string
          format: date-time
          readOnly: true
        end:
          type: string
          format: date-time
          nullable: true
        ongoing:
          type: boolean
      required:
      - contest_number
      - id
      - start
    Discipline:
      type: object
      description: |-
        A ModelSerializer that takes an additional `fields` argument that
        controls which fields should be displayed.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 128
      required:
      - id
      - name
    Scramble:
      type: object
      description: |-
        A ModelSerializer that takes an additional `fields` argument that
        controls which fields should be displayed.
      properties:
        id:
          type: integer
          readOnly: true
        position:
          type: string
          maxLength: 10
        scramble:
          type: string
          maxLength: 512
        extra:
          type: boolean
        contest:
          type: integer
        discipline:
          type: integer
      required:
      - contest
      - discipline
      - extra
      - id
      - position
      - scramble
    SocialLogin:
      type: object
      properties:
        access_token:
          type: string
        code:
          type: string
        id_token:
          type: string
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    UserSerializer01:
      type: object
      description: |-
        A ModelSerializer that takes an additional `fields` argument that
        controls which fields should be displayed.
      properties:
        id:
          type: integer
        username:
          type: string
      required:
      - id
      - username
    contests.SolveLisOutput:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        time_ms:
          type: integer
          nullable: true
        dnf:
          type: boolean
        extra_id:
          type: integer
          nullable: true
        state:
          type: string
          maxLength: 96
        reconstruction:
          type: string
          nullable: true
          maxLength: 15048
        created:
          type: string
          format: date-time
          readOnly: true
        scramble:
          type: integer
        user:
          type: integer
        discipline:
          type: integer
        round_session:
          type: integer
        contest:
          type: integer
      required:
      - contest
      - created
      - discipline
      - id
      - round_session
      - scramble
      - user
    contests.SolveListBestOfEveryUserOutput:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          $ref: '#/components/schemas/UserSerializer01'
        contest:
          $ref: '#/components/schemas/Contest'
        discipline:
          $ref: '#/components/schemas/Discipline'
        time_ms:
          type: integer
          nullable: true
        dnf:
          type: boolean
        extra_id:
          type: integer
          nullable: true
        state:
          type: string
          maxLength: 96
        reconstruction:
          type: string
          nullable: true
          maxLength: 15048
        created:
          type: string
          format: date-time
          readOnly: true
        scramble:
          type: integer
        round_session:
          type: integer
      required:
      - contest
      - created
      - discipline
      - id
      - round_session
      - scramble
      - user
    contests.SolveListBestsInDisciplinesOutput:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          $ref: '#/components/schemas/UserSerializer01'
        contest:
          $ref: '#/components/schemas/Contest'
        discipline:
          $ref: '#/components/schemas/Discipline'
        scramble:
          $ref: '#/components/schemas/Scramble'
        time_ms:
          type: integer
          nullable: true
        dnf:
          type: boolean
        extra_id:
          type: integer
          nullable: true
        state:
          type: string
          maxLength: 96
        reconstruction:
          type: string
          nullable: true
          maxLength: 15048
        created:
          type: string
          format: date-time
          readOnly: true
        round_session:
          type: integer
      required:
      - contest
      - created
      - discipline
      - id
      - round_session
      - scramble
      - user
  securitySchemes:
    jwtCookieAuth:
      type: apiKey
      in: cookie
      name: jwt-auth
    jwtHeaderAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
